apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
spec:
  selector:
    app: {{ .Values.servicename }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
